export const VIDEO_FORMATS = [
  "video/mp4",
  "video/webm",
  "video/ogg",
  "video/x-msvideo",
  "video/x-flv",
  "video/quicktime",
  "video/x-matroska",
  "video/3gpp",
  "video/3gpp2",
  "video/x-ms-wmv",
  "video/x-m4v",
  "video/mpeg",
  "video/mp2t",
  "video/x-ms-asf",
  "video/x-mpegURL",
  "video/x-m4v",
];
